import os
import urllib
import logging
import string

from google.appengine.ext import webapp
from google.appengine.ext.webapp import template
from google.appengine.ext.webapp.util import run_wsgi_app

class MainHandler(webapp.RequestHandler):
	def get(self):

		text = []
		values = {}
		logging.error("HOLY SHIT I'M LOADING")
		self.response.out.write(template.render('index.html', values))
		'''
#Rename everything about blobs
class DisplayResult(webapp.RequestHandler):
	def get(self):
		geneFile = self.request.get("geneFile")
		test=[]
		geneFile.writelines(test);
		
		text = []
		condensedStrings = []
		
		
		for b in blobstore.BlobInfo.all():
			
			
			
			logging.info(b.key())
			blob_reader = blobstore.BlobReader(b.key())
			
			#logging.info(len(blob_reader))
			
			numGenes = 0
			numGenesFound = False
			index = 0

			for line in blob_reader:
				if(not numGenesFound):
					numGenes = int(line.strip().split(' ')[0])
					logging.info(numGenes)
					condensedStrings = [ "" for i in xrange(numGenes) ]
					numGenesFound = True
				elif( not line == ""):
					condensedStrings[index] = condensedStrings[index] + line.strip(' \t\n\r') + " "
					index = (index + 1) % numGenes
				
			blobstore.delete(b.key())
		
		#condensedStrings = ["test ATCGATCGATTAGCTATCGATCGACTCGACTCAG", "test2 ATCGATCGATTAGCTATCGATCGACTCGACTCAG"]
		
		alleles = []
		for condensedString in condensedStrings:
			alleles = ProcessGene(alleles, condensedString)
			logging.info(len(alleles))
		
		values = {'alleles':alleles}
		self.response.out.write(template.render('results.html', values))
		'''
class Demo(webapp.RequestHandler):
	def get(self):
		lines = string.split(DemoFile(), '\n')
		alleles = ProcessFile(lines)
		values = {'alleles':alleles}
		self.response.out.write(template.render('results.html', values))
		
class TestAWESOME(webapp.RequestHandler):
	def post(self):
		test = []
		logging.error("WTF")
		geneFile = self.request.get("geneFile")
		
		lines = string.split(geneFile, '\n')
		
	#	for line in lines:
	#		logging.info(line)
			
		alleles = ProcessFile(lines)
		values = {'alleles':alleles}
		self.response.out.write(template.render('results.html', values))
		
class Gene():
	#parse a raw string from a file into a gene class
	def __init__(self, rawString):
		self.sequence=''
		self.names=[]
		self.delinquent=False
		self.recessive=False;
		
		temp = rawString.split(" ",1)
		logging.info(temp[0])
		self.names.append(temp[0])
		
		if("r" in temp[1] or "re" in temp[1]):
			self.recessive = True
			temp[1].replace("r", "")
			temp[1].replace("e","")
		
		self.sequence = temp[1].strip()
		if("n" in self.sequence):
			self.delinquent = True
		
		index = 1
		result = ""
		for code in self.sequence :
			if(code == "G" or code =="A" or code == "T" or code == "C" or code == "n"):
				if(index % 10 == 0): result += " "
				result += code
				index += 1
		self.sequence = result
		
#pass in a list of already processed genes, and the string for a gene
#parses the new gene, and compares the sequence to the list
#if its sequence is in the porcessed it will make a new entry
def ProcessGene(processedGenes, cString):
	gene = Gene(cString)
	geneFound = False
	
	result = []
	
	for pGene in processedGenes:
		if(pGene.sequence== gene.sequence):
			
			for name in gene.names:
				logging.error(name)
				pGene.names.append(name)
			geneFound = True
		result.append(pGene)

	if(not geneFound):
		result.append(gene)
	
	return result
	
		
def ProcessFile(fileLines):
	numGenes = 0
	numGenesFound = False
	index = 0

	for line in fileLines:
		logging.info(line)
		if(not numGenesFound):
			numGenes = int(line.strip().split(' ')[0])
			logging.error(numGenes)
			condensedStrings = [ "" for i in xrange(numGenes) ]
			numGenesFound = True
		elif( not line == ""):
			condensedStrings[index] = condensedStrings[index] + line.strip(' \t\n\r') + " "
			index = (index + 1) % numGenes

	alleles = []
	for condensedString in condensedStrings:
		logging.info(condensedString)
		alleles = ProcessGene(alleles, condensedString)
		
	return alleles


class Output(webapp.RequestHandler):
	def get(self):
		genes = []
		
		gene1 = Gene("Test1","ATCGATCGATTAGCTATCGATCGACTCGACTCAG")
		gene1.addGene("asdasd")
		gene1.addGene("sdfsdf")
		
		gene2 = Gene("test2", "ATCGATCGATTAGCTATCGATCGACTCGACTCAG")
		gene2.addGene("retert")
		gene2.addGene("yuiyui")
		gene2.addGene("dsfsdfsdfsdfsdf")
		
		genes.append(gene1)
		genes.append(gene2)
		
		values = {'genes':genes}
		self.response.out.write(template.render('results.html', values))
		

def main():
	application = webapp.WSGIApplication(
		  [('/', MainHandler),
		   #('/upload', UploadHandler),
		   #('/results',DisplayResult),
		   ('/output', Output),
		   ('/test', TestAWESOME),
		   ('/demo', Demo)
		  ], debug=True)
	run_wsgi_app(application)

if __name__ == '__main__':
  main()
  
  
def DemoFile():
	return ''' 100 315
CH286-3      GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-7      GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-8      GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-9 re   GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-11 r   GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-12 r   GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-13     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-15 r   GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-18 r   GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-20 r   GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-21     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-23 r   GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-25     GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-27     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-28     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-30 r   GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-33     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-34 r   GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-37     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-40     GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-42 r   GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-45     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-47     GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH286-48     GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH287-4      GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH287-6      GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH287-7      GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH287-8      GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH287-9      GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH287-13     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH287-16     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH287-17     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH287-18     GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH287-23     GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-1      GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-2      GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-3      GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-4      GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-5      GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-6      GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-8      GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-9      GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-11     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-12     GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-14     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-15 r   GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-17     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-21 r   GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-22     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-23     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-24     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-25     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-27     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-30     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-31     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-35     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-36     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-40     GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-42     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-43     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-45     GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-47     GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH288-48     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-1      GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-2 re   GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-4      GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-5      GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-7      GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-9      GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-11     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-14     GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-16     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-19     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-20     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-23     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-24     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-27     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-28     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-33     GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-34     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-37     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-40     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-47     GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-48     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-49     GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-50 r   GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-51     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-52     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-53     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-54     GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-55     GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-56     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-58 r   GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-62     GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-63 r   GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-65 r   GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-66     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-68 r   GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-70 r   GAGAAGCTTG GTCTTGACTT GCTCAGTCAG AGTCCTGTAA GTGGTGTTAA 
CH289-72     GAGAAGCTTG GTCTTGACTT GATCAGTCAG AGTCCTGTAA GTGGTGTTAA 

             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 
             GGAGCCCTGC TCACCTGTCT TGTCCAGTAT GGCTCTGTAG TGGAGAGCAG 

             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 
             CGTTAGGCTT ACAGAAACGC TCCAGCTCCG CCTGCTCTTG ACCCAGCTGA 

             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCATGTT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCATGTT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCATGTT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCATGTT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCATGTT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCATGTT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCATGTT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCATGTT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCATGTT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCATGTT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCATGTT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCATGTT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCATGTT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 
             GGACCTTTGT TCCATGCTTC TGCATTCTTC ACACCCAGCT CAGTGTATCC 

             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATGTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATGTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATGTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATGTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATGTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATGTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATGTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATGTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTCCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTCCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTCCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATGTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATGTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATGTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATGTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATATTCA GCCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATGTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 
             AACATACCTC CCCACAGTGC TGTTGAATCT GATATTTTCA ACCTTATTGA 

             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGGAGTAT 
             AAACATAAGA GTCTATAAAC TCTATACCAT GCAGGTCCTT TGAGAAGTAT 

             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
             CGGAAGCTTC TCGGG
'''